sudo:
  - false
dist:
  - trusty
language:
  - c++
addons:
  apt:
    packages:
    - clang-3.6
compiler:
  - clang
script:
  - CXX=clang++-3.6 CC=clang-3.6 cmake .
  - make -j2
  - ctest --output-on-failure -j1

